name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  golangci:
    name: lint
    strategy:
        matrix:
          lint-folders: [clusterization]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          skip-go-installation: true
          working-directory: ${{ matrix.lint-folders }}
